# Generated by Django 5.1.7 on 2025-03-27 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booklisting',
            name='photo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listings', to='media.photo'),
        ),
    ]
