# Generated by Django 5.1.7 on 2025-05-14 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_booklisting_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='booklisting',
            name='is_sold',
            field=models.BooleanField(default=False),
        ),
    ]
