# Generated by Django 5.1.7 on 2025-05-19 12:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_booklisting_is_sold'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('platform_commission', models.DecimalField(decimal_places=2, max_digits=10)),
                ('seller_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paypal_transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Очікує оплати'), ('PAID', 'Оплачено'), ('SELLER_CONFIRMED', 'Продавець підтвердив відправку'), ('BUYER_CONFIRMED', 'Покупець підтвердив отримання'), ('COMPLETED', 'Завершено'), ('CANCELLED', 'Скасовано'), ('DISPUTED', 'Суперечка')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seller_confirmation_deadline', models.DateTimeField(blank=True, null=True)),
                ('buyer_confirmation_deadline', models.DateTimeField(blank=True, null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='books.booklisting')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to=settings.AUTH_USER_MODEL)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
